import { Template, TemplateFormState } from "@/types";

export function generateMarkdown(template: Template, formState: TemplateFormState): string {
  const lines: string[] = [];

  // Title
  lines.push(`# ${template.name}`);
  lines.push("");
  lines.push(`*Generated by PM Simulator*`);
  lines.push(`*${new Date().toLocaleDateString()}*`);
  lines.push("");
  lines.push(`---`);
  lines.push("");

  // Table of Contents
  lines.push(`## Table of Contents`);
  lines.push("");
  template.sections.forEach((section, index) => {
    const slug = section.title.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
    lines.push(`${index + 1}. [${section.title}](#${slug})`);
  });
  lines.push("");
  lines.push(`---`);
  lines.push("");

  // Document Metadata
  lines.push(`**Generated:** ${new Date().toISOString().split("T")[0]}`);
  lines.push(`**Industry:** ${template.industryId}`);
  lines.push(`**Scenario:** ${template.scenarioId}`);
  lines.push(`**Frameworks:** ${template.frameworkIds.join(", ")}`);
  lines.push("");
  lines.push(`---`);
  lines.push("");

  // Each Section
  template.sections.forEach((section) => {
    const value = formState[section.id];
    if (value && value.trim()) {
      lines.push(`## ${section.title}`);
      lines.push("");
      lines.push(value);
      lines.push("");
    }
  });

  // Footer
  lines.push(`---`);
  lines.push("");
  lines.push(`*This document was created using PM Simulator.*`);

  return lines.join("\n");
}

export function generatePDFContent(template: Template, formState: TemplateFormState): string {
  const sections = template.sections
    .filter((section) => formState[section.id]?.trim())
    .map((section) => {
      const value = formState[section.id]
        .split("\n")
        .map((line: string) => `<p>${line}</p>`)
        .join("");

      return `
        <div style="page-break-inside: avoid; margin-bottom: 32px;">
          <h2 style="font-family: Georgia, serif; font-size: 20px; font-weight: 600; margin-bottom: 16px; border-bottom: 1px solid #e5e5e5; padding-bottom: 8px;">
            ${section.title}
          </h2>
          <div style="font-family: 'IBM Plex Mono', monospace; font-size: 13px; line-height: 1.7; color: #1a1a1a;">
            ${value}
          </div>
        </div>
      `;
    })
    .join("");

  return `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <title>${template.name}</title>
        <style>
          @page {
            size: A4;
            margin: 25mm;
          }
          @media print {
            body { print-color-adjust: exact; -webkit-print-color-adjust: exact; }
          }
          body {
            font-family: 'IBM Plex Mono', 'Fira Code', monospace;
            font-size: 11pt;
            line-height: 1.6;
            color: #1a1a1a;
            max-width: 210mm;
            margin: 0 auto;
            padding: 20px;
          }
          h1 {
            font-family: Georgia, serif;
            font-size: 28px;
            font-weight: 700;
            margin-bottom: 8px;
            color: #000;
          }
          .meta {
            font-size: 11px;
            color: #666;
            margin-bottom: 24px;
            padding-bottom: 16px;
            border-bottom: 2px solid #000;
          }
          h2 {
            font-family: Georgia, serif;
            font-size: 18px;
            font-weight: 600;
            margin-top: 32px;
            margin-bottom: 12px;
            border-bottom: 1px solid #e5e5e5;
            padding-bottom: 6px;
          }
          p {
            margin-bottom: 12px;
            text-align: justify;
          }
          .toc {
            page-break-after: always;
          }
          .toc h2 {
            font-size: 18px;
          }
          .toc ul {
            list-style: none;
            padding-left: 0;
          }
          .toc li {
            padding: 6px 0;
            border-bottom: 1px dotted #ccc;
          }
          .toc a {
            text-decoration: none;
            color: #000;
          }
          .cover {
            text-align: center;
            padding: 80px 20px;
            page-break-after: always;
          }
          .cover h1 {
            font-size: 36px;
            margin-bottom: 16px;
          }
          .cover p {
            font-size: 14px;
            color: #666;
          }
          hr {
            border: none;
            border-top: 1px solid #e5e5e5;
            margin: 24px 0;
          }
        </style>
      </head>
      <body>
        <!-- Cover Page -->
        <div class="cover">
          <h1>${template.name}</h1>
          <p>Product Requirements Document</p>
          <p style="margin-top: 40px; font-size: 12px;">
            Generated by PM Simulator<br>
            ${new Date().toLocaleDateString()}
          </p>
        </div>

        <!-- Table of Contents -->
        <div class="toc">
          <h2>Contents</h2>
          <ul>
            ${template.sections
              .filter((s) => formState[s.id]?.trim())
              .map(
                (section, i) => `
              <li>
                <a href="#section-${i}">${i + 1}. ${section.title}</a>
              </li>
            `
              )
              .join("")}
          </ul>
        </div>

        <!-- Document Body -->
        ${sections}

        <!-- Footer -->
        <hr style="margin-top: 48px;" />
        <p style="font-size: 10px; color: #999; text-align: center;">
          Generated by PM Simulator · Product Management Training Platform
        </p>
      </body>
    </html>
  `;
}

export function generateDocxContent(template: Template, formState: TemplateFormState): string {
  // This generates HTML that can be saved as .docx (Word-compatible)
  const sections = template.sections
    .filter((section) => formState[section.id]?.trim())
    .map((section) => {
      return `
        <w:p>
          <w:pPr>
            <w:pStyle w:val="Heading2"/>
          </w:pPr>
          <w:r>
            <w:t>${section.title}</w:t>
          </w:r>
        </w:p>
        <w:p>
          <w:r>
            <w:t xml:space="preserve">${formState[section.id]?.replace(/\n/g, "</w:t></w:r><w:r><w:t>") || ""}</w:t>
          </w:r>
        </w:p>
      `;
    })
    .join("");

  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Title"/>
      </w:pPr>
      <w:r>
        <w:t>${template.name}</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:r>
        <w:t>Generated: ${new Date().toLocaleDateString()}</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:r>
        <w:t>Industry: ${template.industryId} | Scenario: ${template.scenarioId}</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:r>
        <w:t>Frameworks: ${template.frameworkIds.join(", ")}</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:r>
        <w:t> </w:t>
      </w:r>
    </w:p>
    ${sections}
  </w:body>
</w:document>`;
}

export function generateNotionBlocks(template: Template, formState: TemplateFormState): any[] {
  const blocks: any[] = [];

  // Title block
  blocks.push({
    object: "block",
    type: "heading_1",
    heading_1: {
      rich_text: [
        {
          type: "text",
          text: { content: template.name },
        },
      ],
    },
  });

  // Meta blocks
  blocks.push(
    {
      object: "block",
      type: "paragraph",
      paragraph: {
        rich_text: [
          {
            type: "text",
            text: { content: `Generated: ${new Date().toLocaleDateString()}` },
          },
        ],
      },
    },
    {
      object: "block",
      type: "paragraph",
      paragraph: {
        rich_text: [
          {
            type: "text",
            text: { content: `Industry: ${template.industryId} | Scenario: ${template.scenarioId}` },
          },
        ],
      },
    }
  );

  // Divider
  blocks.push({
    object: "block",
    type: "divider",
    divider: {},
  });

  // Sections
  template.sections.forEach((section) => {
    const value = formState[section.id];
    if (!value?.trim()) return;

    // Section heading
    blocks.push({
      object: "block",
      type: "heading_2",
      heading_2: {
        rich_text: [
          {
            type: "text",
            text: { content: section.title },
          },
        ],
      },
    });

    // Section content (split by lines)
    value.split("\n").forEach((line: string) => {
      if (line.trim()) {
        blocks.push({
          object: "block",
          type: "paragraph",
          paragraph: {
            rich_text: [
              {
                type: "text",
                text: { content: line },
              },
            ],
          },
        });
      }
    });
  });

  return blocks;
}
